import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type {
	Account,
	BalanceAssertion,
	CommodityDefinition,
	Price,
	Transaction,
} from "../types.ts";
import { generateBeancount, writeBeancount } from "./beancount.ts";

const TEST_DIR = join(tmpdir(), "rummage-test-beancount");

const sampleAccounts: Account[] = [
	{ name: "Assets:Bank:Checking", type: "asset", currency: "CZK" },
	{ name: "Expenses:Food", type: "expense" },
	{ name: "Income:Salary", type: "income" },
];

const sampleTransactions: Transaction[] = [
	{
		id: "txn-001",
		date: "2025-12-01",
		amount: { value: 1000, currency: "CZK" },
		description: "Monthly salary",
		account: "Assets:Bank:Checking",
		category: "Income:Salary",
		source: "test",
	},
	{
		id: "txn-002",
		date: "2025-12-05",
		amount: { value: -50, currency: "CZK" },
		description: "Grocery shopping",
		payee: "Supermarket",
		account: "Assets:Bank:Checking",
		category: "Expenses:Food",
		source: "test",
	},
];

describe("generateBeancount", () => {
	test("includes header", () => {
		const output = generateBeancount([], sampleAccounts);

		expect(output).toContain("; Generated by rummage");
		expect(output).toContain('option "operating_currency" "CZK"');
	});

	test("generates account open directives", () => {
		const output = generateBeancount([], sampleAccounts);

		expect(output).toContain("2020-01-01 open Assets:Bank:Checking CZK");
		expect(output).toContain("2020-01-01 open Expenses:Food");
		expect(output).toContain("2020-01-01 open Income:Salary");
	});

	test("uses custom open date if provided", () => {
		const accounts: Account[] = [
			{
				name: "Assets:New",
				type: "asset",
				currency: "EUR",
				opened: "2024-06-15",
			},
		];
		const output = generateBeancount([], accounts);

		expect(output).toContain("2024-06-15 open Assets:New EUR");
	});

	test("generates transactions with payee", () => {
		const output = generateBeancount(sampleTransactions, sampleAccounts);

		expect(output).toContain('2025-12-05 * "Supermarket" "Grocery shopping"');
		expect(output).toContain("Assets:Bank:Checking  -50.00 CZK");
		expect(output).toContain("Expenses:Food");
	});

	test("generates transactions without payee", () => {
		const output = generateBeancount(sampleTransactions, sampleAccounts);

		expect(output).toContain('2025-12-01 * "Monthly salary"');
		expect(output).toContain("Assets:Bank:Checking  1000.00 CZK");
		expect(output).toContain("Income:Salary");
	});

	test("adds tags to transactions", () => {
		const txnWithTags: Transaction[] = [
			{
				id: "txn-003",
				date: "2025-12-10",
				amount: { value: -100, currency: "CZK" },
				description: "Netflix subscription",
				account: "Assets:Bank:Checking",
				category: "Expenses:Subscriptions",
				tags: ["recurring", "monthly"],
				source: "test",
			},
		];
		const output = generateBeancount(txnWithTags, sampleAccounts);

		expect(output).toContain("#recurring #monthly");
	});

	test("groups transactions by month", () => {
		const multiMonthTxns: Transaction[] = [
			{
				id: "txn-jan",
				date: "2025-01-15",
				amount: { value: -10, currency: "CZK" },
				description: "January purchase",
				account: "Assets:Bank",
				category: "Expenses:Other",
				source: "test",
			},
			{
				id: "txn-feb",
				date: "2025-02-20",
				amount: { value: -20, currency: "CZK" },
				description: "February purchase",
				account: "Assets:Bank",
				category: "Expenses:Other",
				source: "test",
			},
		];
		const output = generateBeancount(multiMonthTxns, sampleAccounts);

		expect(output).toContain("; === 2025-01 ===");
		expect(output).toContain("; === 2025-02 ===");
	});

	test("sorts transactions by date", () => {
		const unsortedTxns: Transaction[] = [
			{
				id: "txn-later",
				date: "2025-12-20",
				amount: { value: -10, currency: "CZK" },
				description: "Later",
				account: "Assets:Bank",
				category: "Expenses:Other",
				source: "test",
			},
			{
				id: "txn-earlier",
				date: "2025-12-05",
				amount: { value: -20, currency: "CZK" },
				description: "Earlier",
				account: "Assets:Bank",
				category: "Expenses:Other",
				source: "test",
			},
		];
		const output = generateBeancount(unsortedTxns, sampleAccounts);

		const earlierIndex = output.indexOf("Earlier");
		const laterIndex = output.indexOf("Later");

		expect(earlierIndex).toBeLessThan(laterIndex);
	});

	test("escapes quotes in description", () => {
		const txnWithQuotes: Transaction[] = [
			{
				id: "txn-quotes",
				date: "2025-12-01",
				amount: { value: -10, currency: "CZK" },
				description: 'Book: "The Great Gatsby"',
				account: "Assets:Bank",
				category: "Expenses:Books",
				source: "test",
			},
		];
		const output = generateBeancount(txnWithQuotes, sampleAccounts);

		expect(output).toContain('\\"The Great Gatsby\\"');
	});

	test("uses Uncategorized for missing category", () => {
		const uncategorizedTxn: Transaction[] = [
			{
				id: "txn-uncat",
				date: "2025-12-01",
				amount: { value: -10, currency: "CZK" },
				description: "Unknown purchase",
				account: "Assets:Bank",
				source: "test",
			},
		];
		const output = generateBeancount(uncategorizedTxn, sampleAccounts);

		expect(output).toContain("Expenses:Uncategorized");
	});

	test("uses ! flag for pending transactions", () => {
		const pendingTxn: Transaction[] = [
			{
				id: "txn-pending",
				date: "2025-12-01",
				amount: { value: -10, currency: "CZK" },
				description: "Pending payment",
				account: "Assets:Bank",
				pending: true,
				source: "test",
			},
			{
				id: "txn-cleared",
				date: "2025-12-01",
				amount: { value: -20, currency: "CZK" },
				description: "Cleared payment",
				account: "Assets:Bank",
				source: "test",
			},
		];
		const output = generateBeancount(pendingTxn, sampleAccounts);

		expect(output).toContain('2025-12-01 ! "Pending payment"');
		expect(output).toContain('2025-12-01 * "Cleared payment"');
	});

	test("includes transaction metadata", () => {
		const txnWithMetadata: Transaction[] = [
			{
				id: "revolut-abc123",
				date: "2025-12-01",
				amount: { value: -29.95, currency: "USD" },
				originalAmount: { value: -614.9, currency: "CZK" },
				description: "Coffee Shop",
				account: "Assets:Revolut:USD",
				category: "Expenses:Food:Restaurants",
				source: "/path/to/USD_2025.json",
				metadata: {
					revolutType: "CARD_PAYMENT",
					revolutState: "COMPLETED",
					revolutCategory: "restaurants",
					rate: 20.53,
					merchant: {
						name: "Coffee Shop",
						mcc: "5812",
						category: "restaurants",
						city: "Prague",
						country: "CZ",
					},
				},
			},
		];
		const output = generateBeancount(txnWithMetadata, []);

		// Core metadata
		expect(output).toContain('id: "revolut-abc123"');
		expect(output).toContain('source: "USD_2025.json"');
		expect(output).toContain('original-amount: "-614.90 CZK"');

		// Bank-specific metadata
		expect(output).toContain('revolut-type: "CARD_PAYMENT"');
		expect(output).toContain('revolut-state: "COMPLETED"');
		expect(output).toContain("rate: 20.53");

		// Flattened merchant metadata
		expect(output).toContain('merchant-name: "Coffee Shop"');
		expect(output).toContain('merchant-mcc: "5812"');
		expect(output).toContain('merchant-city: "Prague"');
	});

	test("generates transfer transactions with explicit amounts and cost", () => {
		const transferTxn: Transaction[] = [
			{
				id: "txn-exchange",
				date: "2025-12-01",
				amount: { value: -50, currency: "EUR" },
				description: "Exchange EUR to CZK",
				account: "Assets:Revolut:EUR",
				source: "test",
				transfer: {
					toAccount: "Assets:Revolut:CZK",
					toAmount: { value: 1250, currency: "CZK" },
				},
			},
		];
		const output = generateBeancount(transferTxn, []);

		expect(output).toContain('2025-12-01 * "Exchange EUR to CZK"');
		expect(output).toContain("Assets:Revolut:EUR  -50.00 EUR");
		// The destination posting should include total cost (@@ syntax) for beancount balancing
		expect(output).toContain("Assets:Revolut:CZK  1250.00 CZK @@ 50.00 EUR");
		// Transfer transaction body should NOT have Expenses:Uncategorized as counter
		const transactionSection = output.split("; === 2025-12 ===")[1];
		expect(transactionSection).not.toContain("Expenses:Uncategorized");
	});

	test("generates commodity purchase transactions", () => {
		const commodityTxn: Transaction[] = [
			{
				id: "fund-buy-2025-03-13-500",
				date: "2025-03-13",
				amount: { value: -1000.5, currency: "CZK" },
				description: "Buy fund units",
				payee: "Fund Manager",
				account: "Assets:Investments:Fund:Cash",
				source: "test",
				commodity: {
					account: "Assets:Investments:Fund",
					symbol: "TESTFUND",
					units: 500,
					costPerUnit: { value: 2.001, currency: "CZK" },
				},
			},
		];
		const output = generateBeancount(commodityTxn, []);

		// Cash side
		expect(output).toContain("Assets:Investments:Fund:Cash  -1000.50 CZK");
		// Commodity side with cost basis (4 decimal places)
		expect(output).toContain(
			"Assets:Investments:Fund  500 TESTFUND {2.0010 CZK}",
		);
		// Should NOT have Expenses:Uncategorized
		const txnSection = output.split("; === 2025-03 ===")[1];
		expect(txnSection).not.toContain("Expenses:Uncategorized");
		// Both accounts should be opened
		expect(output).toContain("open Assets:Investments:Fund:Cash");
		expect(output).toContain("open Assets:Investments:Fund");
	});

	test("generates commodity definitions", () => {
		const commodities: CommodityDefinition[] = [
			{
				symbol: "TESTFUND",
				name: "Test Real Estate Fund (CZK)",
				isin: "CZ0000000001",
				date: "2021-02-28",
			},
		];
		const output = generateBeancount(
			[],
			[],
			undefined,
			undefined,
			undefined,
			undefined,
			commodities,
		);

		expect(output).toContain("; Commodities");
		expect(output).toContain("2021-02-28 commodity TESTFUND");
		expect(output).toContain('name: "Test Real Estate Fund (CZK)"');
		expect(output).toContain('isin: "CZ0000000001"');
	});

	test("generates balance assertions", () => {
		const balanceAssertions: BalanceAssertion[] = [
			{
				date: "2025-12-31",
				account: "Assets:Revolut:CZK",
				balance: { value: 5000, currency: "CZK" },
				source: "test",
			},
			{
				date: "2025-12-31",
				account: "Assets:Bank:Checking",
				balance: { value: 10000, currency: "CZK" },
				source: "test",
			},
		];
		const output = generateBeancount([], [], balanceAssertions);

		expect(output).toContain("; Balance Assertions");
		expect(output).toContain("2025-12-31 balance Assets:Revolut:CZK 5000 CZK");
		expect(output).toContain(
			"2025-12-31 balance Assets:Bank:Checking 10000 CZK",
		);
	});

	test("sorts balance assertions by date", () => {
		const balanceAssertions: BalanceAssertion[] = [
			{
				date: "2025-12-31",
				account: "Assets:Bank",
				balance: { value: 1000, currency: "CZK" },
			},
			{
				date: "2025-06-30",
				account: "Assets:Bank",
				balance: { value: 500, currency: "CZK" },
			},
		];
		const output = generateBeancount([], [], balanceAssertions);

		const june = output.indexOf("2025-06-30");
		const dec = output.indexOf("2025-12-31");
		expect(june).toBeLessThan(dec);
	});

	test("generates price directives", () => {
		const prices: Price[] = [
			{
				date: "2025-12-01",
				baseCurrency: "EUR",
				quoteCurrency: "CZK",
				price: 25.0,
				source: "test",
			},
		];
		const output = generateBeancount([], [], [], prices);

		expect(output).toContain("; Prices");
		expect(output).toContain("2025-12-01 price EUR 25.00 CZK");
	});

	test("deduplicates prices by date and currency pair", () => {
		const prices: Price[] = [
			{
				date: "2025-12-01",
				baseCurrency: "EUR",
				quoteCurrency: "CZK",
				price: 25.0,
			},
			{
				date: "2025-12-01",
				baseCurrency: "EUR",
				quoteCurrency: "CZK",
				price: 25.1, // duplicate date/pair, should be ignored
			},
			{
				date: "2025-12-02",
				baseCurrency: "EUR",
				quoteCurrency: "CZK",
				price: 25.2, // different date, should be included
			},
		];
		const output = generateBeancount([], [], [], prices);

		// Should only have 2 price directives
		const priceMatches = output.match(/^\d{4}-\d{2}-\d{2} price /gm);
		expect(priceMatches?.length).toBe(2);
		expect(output).toContain("2025-12-01 price EUR 25.00 CZK");
		expect(output).toContain("2025-12-02 price EUR 25.20 CZK");
	});

	test("places prices after accounts and before transactions", () => {
		const prices: Price[] = [
			{
				date: "2025-12-01",
				baseCurrency: "EUR",
				quoteCurrency: "CZK",
				price: 25.0,
			},
		];
		const output = generateBeancount(
			sampleTransactions,
			sampleAccounts,
			[],
			prices,
		);

		const accountsIndex = output.indexOf("; Accounts");
		const pricesIndex = output.indexOf("; Prices");
		const transactionsIndex = output.indexOf("; === 2025-12 ===");

		expect(accountsIndex).toBeLessThan(pricesIndex);
		expect(pricesIndex).toBeLessThan(transactionsIndex);
	});

	test("places balance assertions after transactions", () => {
		const balanceAssertions: BalanceAssertion[] = [
			{
				date: "2025-12-31",
				account: "Assets:Bank",
				balance: { value: 1000, currency: "CZK" },
			},
		];
		const output = generateBeancount(
			sampleTransactions,
			sampleAccounts,
			balanceAssertions,
		);

		const transactionsIndex = output.indexOf("; === 2025-12 ===");
		const balanceIndex = output.indexOf("; Balance Assertions");

		expect(transactionsIndex).toBeLessThan(balanceIndex);
	});

	test("generates opening balance transactions", () => {
		const openingBalances: BalanceAssertion[] = [
			{
				date: "2025-01-01",
				account: "Assets:Revolut:CZK",
				balance: { value: 5000, currency: "CZK" },
				source: "/path/to/CZK_2025.json",
			},
		];
		const output = generateBeancount([], [], [], [], openingBalances);

		expect(output).toContain("; Opening Balances");
		expect(output).toContain('2025-01-01 * "Opening Balance" ^opening');
		expect(output).toContain("Assets:Revolut:CZK  5000.00 CZK");
		expect(output).toContain("Equity:Opening-Balances");
		expect(output).toContain('source: "CZK_2025.json"');
	});

	test("deduplicates opening balances by account, keeping earliest", () => {
		const openingBalances: BalanceAssertion[] = [
			{
				date: "2025-02-01",
				account: "Assets:Bank",
				balance: { value: 2000, currency: "CZK" },
			},
			{
				date: "2025-01-01",
				account: "Assets:Bank",
				balance: { value: 1000, currency: "CZK" },
			},
		];
		const output = generateBeancount([], [], [], [], openingBalances);

		// Should only have one opening balance entry for Assets:Bank
		const openingMatches = output.match(/Assets:Bank\s+\d+\.\d+ CZK/g);
		expect(openingMatches?.length).toBe(1);
		// Should use the earlier date's balance (1000 CZK from 2025-01-01)
		expect(output).toContain("Assets:Bank  1000.00 CZK");
		expect(output).not.toContain("Assets:Bank  2000.00 CZK");
	});

	test("places opening balances after prices and before transactions", () => {
		const prices: Price[] = [
			{
				date: "2025-01-01",
				baseCurrency: "EUR",
				quoteCurrency: "CZK",
				price: 25.0,
			},
		];
		const openingBalances: BalanceAssertion[] = [
			{
				date: "2025-01-01",
				account: "Assets:Bank",
				balance: { value: 1000, currency: "CZK" },
			},
		];
		const output = generateBeancount(
			sampleTransactions,
			sampleAccounts,
			[],
			prices,
			openingBalances,
		);

		const pricesIndex = output.indexOf("; Prices");
		const openingIndex = output.indexOf("; Opening Balances");
		const transactionsIndex = output.indexOf("; === 2025-12 ===");

		expect(pricesIndex).toBeLessThan(openingIndex);
		expect(openingIndex).toBeLessThan(transactionsIndex);
	});
});

describe("writeBeancount", () => {
	afterEach(() => {
		rmSync(TEST_DIR, { recursive: true, force: true });
	});

	test("writes beancount file to disk", () => {
		mkdirSync(TEST_DIR, { recursive: true });

		const filePath = join(TEST_DIR, "output.beancount");
		const txns: Transaction[] = [
			{
				id: "txn-write-test",
				date: "2025-12-01",
				amount: { value: -50, currency: "CZK" },
				description: "Test write",
				account: "Assets:Bank",
				category: "Expenses:Test",
				source: "test",
			},
		];

		writeBeancount(filePath, txns, sampleAccounts);

		const content = readFileSync(filePath, "utf-8");
		expect(content).toContain("; Generated by rummage");
		expect(content).toContain("Test write");
		expect(content).toContain("-50.00 CZK");
	});
});
